server:
  port: 8081  # 修改端口号
  servlet:
    context-path: /pmp-ai-analysis
spring:
  application:
    name: pmp-ai-analysis  # 应用名称
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://60.205.166.16:3306/pmp_ai_analysis?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: Zc@123456
    driver-class-name: com.mysql.jdbc.Driver

# 指定 MyBatis XML 映射文件的位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml