# 配置文件（生产环境）
server:
  ip: 127.0.0.1
  port: 8081
  servlet:
    context-path: /pmp-ai-analysis

spring:
  application:
    # 应用名称
    name: pmp-ai-analysis
  # 数据库连接配置
  datasource:
    pmp-ai-analysis:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${server.ip}:3306/pmp_ai_analysis?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Zc@123456
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

# redis相关
redis.addrs: ${server.ip}:6379
redis.passwd: 123456
redis.cluster:

# 日志相关
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core: debug

# 自定义参数
# 文件上传地址
document:
  upload:
    path: /mc/opt/upload/

# 模型地址
ai:
  model:
    analysis:
      path: http://192.168.5.126:8000/ct-module/dicom/analysis
    pci:
      path: http://127.0.0.1:8509/genpci
#      path: http://192.168.5.126:8509/genpci

# 是否是开发环境
isDev: false